[package]
name = "stampcollect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etagere = "0.2.8"
walkdir = "2.4.0"

[workspace]
members = ["stampcollect-sf2g"]
